name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Runs when code is pushed to 'main' branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_USERNAME }}" | docker login -u "${{ secrets.DOCKER_PASSWORD }}" --password-stdin

      - name: Build the Docker image
        run: docker build -t mydockerhubusername/myapp:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push mydockerhubusername/myapp:latest
